import streamlit as st
import tensorflow as tf
from PIL import Image, ImageOps
import numpy as np
import pandas as pd
import time
import base64
from io import BytesIO

st.set_page_config(page_title="Iron Pulse", layout="wide")

# Inject custom CSS for theme and scanner animation
st.markdown("""
<style>
:root {
    --primary: rgb(178,34,34);
    --dark: rgb(139,0,0);
    --white: #ffffff;
}
.stButton>button {
    border: 2px solid var(--primary) !important;
    color: var(--primary) !important;
    background-color: transparent !important;
    transition: 0.3s;
}
.stButton>button:hover {
    background-color: var(--primary) !important;
    color: var(--white) !important;
    border-color: var(--primary) !important;
}
.scanner-container {
    position: relative;
    display: inline-block;
    width: 100%;
    max-width: 400px;
}
.scanner-overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(178, 34, 34, 0.3);
    overflow: hidden;
    pointer-events: none;
}
.scanner-bar {
    width: 100%;
    height: 4px;
    background-color: rgb(178,34,34);
    position: absolute;
    animation: scan 2s infinite linear;
}
@keyframes scan {
    0% { top: 0; }
    50% { top: 100%; }
    100% { top: 0; }
}
</style>
""", unsafe_allow_html=True)

# Initialize session state variables
if 'agreed' not in st.session_state:
    st.session_state.agreed = False
if 'logged_in' not in st.session_state:
    st.session_state.logged_in = False
if 'users' not in st.session_state:
    st.session_state.users = {}
if 'history' not in st.session_state:
    st.session_state.history = []

# Load model and labels
@st.cache_resource
def load_diagnostic_tool(model_path, label_path):
    model = tf.keras.models.load_model(model_path, compile=False)
    with open(label_path, "r") as f:
        class_names = [line.strip() for line in f.readlines()]
    return model, class_names

# Render image with scanner overlay
def render_scanned_image(pil_img):
    buffered = BytesIO()
    pil_img.save(buffered, format="JPEG")
    img_str = base64.b64encode(buffered.getvalue()).decode()
    html = f"""
    <div class="scanner-container">
        <img src="data:image/jpeg;base64,{img_str}" width="100%" style="border-radius: 8px;">
        <div class="scanner-overlay">
            <div class="scanner-bar"></div>
        </div>
    </div>
    """
    st.markdown(html, unsafe_allow_html=True)

# Screen 1: Disclaimer
if not st.session_state.agreed:
    st.title("Disclaimer")
    st.write("Please note that this application is for symptom tracking only and does not provide a medical diagnosis. Results are informational and should not replace a clinician's evaluation or laboratory testing. The information generated by this tool is based on available data inputs and analysis. Accuracy may vary, and results may be subject to limitations inherent to the data provided. This tool is not intended for use in emergency situations or as the basis for critical patient management decisions. If you are displaying concerning symptoms or have a family history of iron disorders, please seek professional medical advice. This tool may miss conditions or flag normal findings and is therefore not a substitute for medical care.")
    if st.button("I Agree"):
        st.session_state.agreed = True
        st.rerun()

# Screen 2: Login / Signup
elif not st.session_state.logged_in:
    st.title("Access Portal")
    tab1, tab2 = st.tabs(["Login", "Sign Up"])
    
    with tab1:
        st.subheader("Log In")
        log_user = st.text_input("Username", key="log_user")
        log_pass = st.text_input("Password", type="password", key="log_pass")
        if st.button("Login"):
            if log_user in st.session_state.users and st.session_state.users[log_user] == log_pass:
                st.session_state.logged_in = True
                st.rerun()
            else:
                st.error("Invalid credentials.")
                
    with tab2:
        st.subheader("Create Account")
        sign_user = st.text_input("Email/Username (Must contain @)", key="sign_user")
        sign_pass = st.text_input("Password", type="password", key="sign_pass")
        if st.button("Sign Up"):
            if "@" not in sign_user:
                st.error("Username must contain an '@' symbol.")
            elif sign_user in st.session_state.users:
                st.error("User already exists.")
            elif len(sign_pass) < 1:
                st.error("Please enter a password.")
            else:
                st.session_state.users[sign_user] = sign_pass
                st.success("Account created. Please log in.")

# Screen 3: Main Application
else:
    st.sidebar.title("Iron Pulse Suite")
    nav = st.sidebar.radio("Navigation", 
                           ["Diagnostic Tool", 
                            "Tracker & Trends", 
                            "Location & Labs", 
                            "Education", 
                            "FAQ"])
    
    if st.sidebar.button("Log Out"):
        st.session_state.logged_in = False
        st.rerun()

    if nav == "Diagnostic Tool":
        mode = st.radio("Select Diagnostic Mode", 
                        ["Conjunctival Pallor (Eyes)", 
                         "Dermal Bronzing (Skin)", 
                         "Nailbed Scanning (Nails)"])

        # Map selection to files
        if mode == "Conjunctival Pallor (Eyes)":
            m_file, l_file = "model_eyes.h5", "labels_eyes.txt"
        elif mode == "Dermal Bronzing (Skin)":
            m_file, l_file = "model_skin.h5", "labels_skin.txt"
        else:
            m_file, l_file = "model_nails.h5", "labels_nails.txt"

        current_model, labels = load_diagnostic_tool(m_file, l_file)

        st.title(f"Mode: {mode}")
        img_file = st.camera_input("Scan Target")

        if img_file:
            image = Image.open(img_file).convert("RGB")
            size = (224, 224)
            image = ImageOps.fit(image, size, Image.Resampling.LANCZOS)
            
            # Show scanner animation
            st.write("Analyzing tissue density and pigmentation...")
            render_scanned_image(image)
            time.sleep(2) # Simulate processing time
            
            img_array = np.asarray(image)
            
            # Normalize for network
            normalized_image = (img_array.astype(np.float32) / 127.5) - 1
            data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
            data[0] = normalized_image

            prediction = current_model.predict(data)
            index = np.argmax(prediction)
            confidence = prediction[0][index]
            
            raw_label = labels[index]
            clean_label = raw_label.split(' ', 1)[-1].split(': ')[-1]

            st.divider()
            st.subheader("Analysis Results")
            st.write(f"Result: **{clean_label}**")
            st.write(f"Confidence: **{round(confidence * 100, 2)}%**")

    elif nav == "Tracker & Trends":
        st.title("Blood Test & Sensor Tracking")
        
        st.write("### Reference Ranges")
        st.write("Men: 65 to 176 micrograms per deciliter (mcg/dL).")
        st.write("Women: 50 to 170 mcg/dL.")
        st.write("Children: 50 to 120 mcg/dL.")
        st.write("Infants: 100 to 250 mcg/dL.")
        st.write("A typical serum iron reference range is roughly 60 to 140 mcg/dL in many labs, though ranges vary. Transferrin saturation is often considered normal around 20% to 50%. For hemochromatosis, ferritin and transferrin saturation are especially important. Ferritin above 300 ng/mL in men or 200 ng/mL in women, together with transferrin saturation above 45%, is highly suggestive of hereditary hemochromatosis.")
        
        st.divider()
        st.write("### Enter New Reading")
        
        # Hypothetical hardware sensor integration code
        # To integrate physical sensor:
        # 1. import serial
        # 2. ser = serial.Serial('COM_PORT', 9600)
        # 3. raw_data = ser.readline().decode('utf-8').strip()
        # 4. iron_val = float(raw_data)
        
        col1, col2 = st.columns(2)
        with col1:
            date_input = st.date_input("Date")
            serum_iron = st.number_input("Serum Iron (mcg/dL)", min_value=0.0, format="%.1f")
        with col2:
            ferritin = st.number_input("Ferritin (ng/mL)", min_value=0.0, format="%.1f")
            transferrin = st.number_input("Transferrin Saturation (%)", min_value=0.0, format="%.1f")
            
        if st.button("Log Results"):
            st.session_state.history.append({
                "Date": date_input,
                "Serum Iron": serum_iron,
                "Ferritin": ferritin,
                "Transferrin": transferrin
            })
            st.success("Results logged successfully.")
            
        if st.session_state.history:
            st.divider()
            st.write("### Your Trends")
            
            # Evaluate latest entry
            latest = st.session_state.history[-1]
            st.write(f"**Latest Evaluation ({latest['Date']}):**")
            
            if latest['Ferritin'] > 300 or latest['Transferrin'] > 45:
                st.error("Alert: Ferritin or Transferrin levels are elevated. This is suggestive of iron overload. Please consult a clinician.")
            elif latest['Serum Iron'] < 50:
                st.warning("Alert: Serum iron is below standard ranges. This may suggest anemia. Please consult a clinician.")
            else:
                st.success("Levels appear to be within standard reference ranges.")

            # Create graph
            df = pd.DataFrame(st.session_state.history)
            df.set_index("Date", inplace=True)
            st.line_chart(df)
            st.dataframe(df)

    elif nav == "Location & Labs":
        st.title("Find a Phlebotomy Center")
        if st.button("Detect Location"):
            st.success("Location Detected: Milton, Ontario, Canada")
            
            st.write("### Nearby Facilities")
            st.write("**1. Milton District Hospital (Labs)**")
            st.write("Address: 725 Bronte St S, Milton, ON L9T 9K1")
            st.write("**2. LifeLabs**")
            st.write("Address: 400 Bronte St S, Milton, ON L9T 0H7")
            
            st.divider()
            st.write("### Pre-Test Instructions")
            st.write("Follow instructions from the clinic or lab. Some iron studies may require fasting for 12 hours prior. Drink plenty of water to make blood draws easier. Confirm preparation instructions with the testing site directly.")
            
            st.write("### Cost Estimates")
            st.write("Prices vary by location, test type, and insurance coverage. The following are estimates rather than guaranteed costs:")
            st.write("Basic CBC: $15 to $30")
            st.write("Comprehensive Iron Panel: $40 to $80")
            st.write("OHIP Coverage: Standard iron panels are typically fully covered in Ontario with a valid physician requisition.")

    elif nav == "Learn More About Hemochromatosis and Anemia":
        st.title("Education Center")
        st.subheader("Anemia")
        st.write("The oxygen supply is reduced when the body has fewer red blood cells or hemoglobin than normal. Anemia is the term for this condition. Common symptoms include weakness, exhaustion, confusion, dyspnea, pale skin or inner eyelids, and sometimes a fast heartbeat. Iron deficiency is one of the most common causes of anemia, while other causes include bleeding, chronic illness, renal disease, vitamin deficiencies, and genetic illnesses.")
        
        st.divider()
        st.subheader("Hemochromatosis")
        st.write("Although hemochromatosis is typically brought on by genetic alterations, it can also be acquired and is referred to as secondary hemochromatosis. The body absorbs too much iron due to hemochromatosis, which can accumulate in the liver, pancreas, heart, joints, skin, and endocrine organs. Fatigue, joint discomfort, abdominal pain, diabetes, heart rhythm issues, liver illness, and bronze or gray skin pigmentation are typical symptoms. Blood tests that reveal increased ferritin and transferrin saturation are frequently used to identify it. It may be brought on by another illness, such as liver disease or excessive alcohol consumption, that causes the intestines to absorb too much iron. Alternatively, it may occur if you receive excessive amounts of iron, such as from receiving too many blood transfusions. Secondary iron excess can eventually harm organs as well.")

    elif nav == "FAQ":
        st.title("Frequently Asked Questions")
        
        st.write("**What does this application assist with?**")
        st.write("It helps you track symptoms, blood test results, treatment history, and appointments, and it can provide educational information about anemia and hemochromatosis.")
        
        st.write("**Can the app diagnose anemia or hemochromatosis?**")
        st.write("No. It can only support screening and tracking. Anemia is diagnosed using blood counts such as hemoglobin and hematocrit, while hemochromatosis is usually screened for with laboratory tests such as ferritin and transferrin saturation.")
        
        st.write("**Can I use the app instead of seeing a doctor?**")
        st.write("No, the app is not a substitute for medical care. If the app flags symptoms or your symptoms are worsening, you should talk to a clinician.")
        
        st.write("**Why does the app ask for blood test results?**")
        st.write("Blood tests are the most important part of evaluating both conditions. Symptom tracking and skin or eye analysis may help identify patterns, but they cannot confirm disease on their own.")
        
        st.write("**What should I do before a blood test?**")
        st.write("Follow the instructions from the clinic or lab, which can be found in-app. Some iron studies may require fasting or specific timing, and the app can remind users to confirm preparation instructions with the testing site.")
        
        st.write("**Can the app estimate costs?**")
        st.write("The app can show estimates, but prices vary by location, test type, and insurance coverage, so the app should label them as estimates rather than guaranteed costs.")